spring:
  application:
    name: lab
  datasource:
    url: jdbc:mysql://localhost:3306/test_db
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  liquibase:
    change-log: db/changelog/db.changelog-master.xml

server:
  port: 9993
